<h2 style = "color:green">INTRODUCTION

<div style = "background-color:lightblue; color:green; font-size:20px; text-align:justify">The Indian technology job market is evolving rapidly, driven by growing demand for data, artificial intelligence, cloud computing, and software development professionals. This dataset provides a comprehensive view of the Indian tech hiring landscape in 2025, containing 23,201 real job listings collected from Naukri.com across major Indian cities and remote locations. It includes information on job roles, salary ranges, required skills, experience levels, work modes, company characteristics, and skill domains. Through Exploratory Data Analysis (EDA), this project aims to uncover hiring trends, salary patterns, skill demands, and geographical differences across various technology roles, providing valuable insights for job seekers, recruiters, and industry professionals.

<h2 style = "color:green">OBJECTIVES:

<div style = "background-color:lightblue; color:green; font-size:20px; text-align:justify">
<ul>

<li>Analyze the distribution of tech job opportunities across different roles and cities.</li>
<li>Explore salary trends and identify factors influencing compensation.</li>
<li>Examine the demand for various technical skills and skill domains.
<li>Compare hiring patterns across Remote, Hybrid, and On-site work modes.
<li>Investigate experience-level requirements and opportunities for freshers and senior professionals.
<li>Identify cities and roles with the highest concentration of job openings.
<li>Generate actionable insights into the Indian tech job market to support career planning and workforce analysis.

</ul>
</div>

<h3 style = "color:green">1. Getting Ready with Data

In [1]:
import numpy as np
import pandas as pd
import polars as pl

import matplotlib.pyplot as plt
import seaborn as sns
import seaborn.objects as so

In [3]:
data = pl.read_csv('/home/kartika/Datasets/indian_tech_jobs_2026.csv')
data = data.to_pandas()

In [4]:
data.head()

   job_id  ... salary_negotiable
0       1  ...             False
1       2  ...             False
2       3  ...             False
3       4  ...             False
4       5  ...             False

[5 rows x 32 columns]

In [5]:
data.tail()

       job_id  ... salary_negotiable
23196   23197  ...             False
23197   23198  ...             False
23198   23199  ...             False
23199   23200  ...             False
23200   23201  ...             False

[5 rows x 32 columns]

In [8]:
data.drop(
    ['job_id', 'posted_date_raw', 'job_url',
      'data_source', 'scraped_at', 'salary_midpoint_lpa',
      'days_since_posted'], axis = 'columns', inplace = True
)

<div style = "background-color:lightblue; color:green; font-size:20px; text-align:justify">Dropped irrelevant columns.

In [10]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23201 entries, 0 to 23200
Data columns (total 25 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   job_title            23201 non-null  object
 1   company_name         23201 non-null  object
 2   company_rating       23201 non-null  float64
 3   location             23201 non-null  object
 4   scraped_city         23201 non-null  object
 5   role_category        23201 non-null  object
 6   experience_raw       23201 non-null  object
 7   experience_min_yrs   23201 non-null  float64
 8   experience_max_yrs   23201 non-null  float64
 9   salary_raw           23201 non-null  object
 10  salary_min_lpa       23201 non-null  float64
 11  salary_max_lpa       23201 non-null  float64
 12  salary_disclosed     23201 non-null  bool
 13  skills_required      23201 non-null  object
 14  skills_count         23201 non-null  int64
 15  job_description      23201 non-null  object
 16  work_mode            23201 non-null  object
 17  company_size_bucket  23201 non-null  object
 18  salary_tier          23201 non-null  object
 19  experience_tier      23201 non-null  object
 20  is_senior            23201 non-null  bool
 21  primary_city         23201 non-null  object
 22  skill_domain         23201 non-null  object
 23  is_fresher_friendly  23201 non-null  bool
 24  salary_negotiable    23201 non-null  bool
dtypes: bool(4), float64(5), int64(1), object(15)
memory usage: 3.8+ MB

In [11]:
data.isnull().sum()

job_title              0
company_name           0
company_rating         0
location               0
scraped_city           0
role_category          0
experience_raw         0
experience_min_yrs     0
experience_max_yrs     0
salary_raw             0
salary_min_lpa         0
salary_max_lpa         0
salary_disclosed       0
skills_required        0
skills_count           0
job_description        0
work_mode              0
company_size_bucket    0
salary_tier            0
experience_tier        0
is_senior              0
primary_city           0
skill_domain           0
is_fresher_friendly    0
salary_negotiable      0
dtype: int64

<div style = "background-color:lightblue; color:green; font-size:20px; text-align:justify">No null values.

In [12]:
data.duplicated().sum()

np.int64(0)

<div style = "background-color:lightblue; color:green; font-size:20px; text-align:justify">No duplicate values.

<div>

<h3 style = "color:green">2. Univariate Analysis